apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    key1: value1
    key2: value2
  name: mynginx2
spec:
  containers:
  - image: nginx:1.25.3-alpine
    name: mynginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
