apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-dev
  name: nginx-dev
spec:
  containers:
  - image: nginx
    name: nginx-dev
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
