apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: shared
  annotations:
provisioner: hostpath.ci.k8s.io
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /srv/app-data
  storageClassName: shared
