apiVersion: v1
kind: Pod
metadata:
  name: multi-cont-pod
spec:
  containers:
  - image: busybox
    name: multi-container
    command: ['sh', '-c', "while true; do echo 'Hi I am from Main container' >> /var/log/index.html; sleep 5; done"]
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - image: nginx
    name: sidecar-container
    ports:
    - containerPort: 80
    volumeMounts:
    - name: varlog
      mountPath: /usr/share/nginx/html
  volumes:
  - name: varlog
    emptyDir: {}
  restartPolicy: Always
