apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox-container1
    command: ['sh', '-c', 'ls; sleep 3600']
    volumeMounts:
    - name: echolog
      mountPath: /var/log
  - image: busybox
    name: busybox-container2
    command: ['sh', '-c', 'echo Hello World; sleep 3600;']
    volumeMounts:
    - name: echolog
      mountPath: /var/log
  - image: busybox
    name: busybox-container3
    command: ['sh', '-c', 'echo this is the third container; sleep 3600']
    volumeMounts:
    - name: echolog
      mountPath: /var/log
  volumes:
  - name: echolog
    emptyDir: {}
  restartPolicy: Always
