apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mynode
  name: mynode-pod
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node2
  containers:
  - image: dbgurum/mynode:1.0
    name: mynode-pod
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
