apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sch-test1
  name: sch-test1
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-node1
  containers:
  - image: nginx:1.25.3
    name: sch-test1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
