apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sch-test2
  name: sch-test2
spec:
  nodeSelector:
    cputype: gpu
  containers:
  - image: nginx:1.25.3
    name: sch-test2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
