apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-envfrom-pod
  name: cm-envfrom-pod
spec:
  containers:
  - image: nginx:1.25.3-alpine
    name: cm-envfrom-pod
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: k8s-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
